#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/include/esp_lcd_types.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/include/esp_lcd_panel_rgb.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/include/esp_lcd_panel_io.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/include/esp_lcd_panel_ops.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/include/esp_lcd_panel_vendor.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/include/esp_lcd_panel_commands.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/interface/esp_lcd_panel_interface.h"
#include ".embuild/espressif/esp-idf/release-v5.1/components/esp_lcd/interface/esp_lcd_panel_io_interface.h"
